In [ ]:
import numpy as np
import pandas as pd
from skleran.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [28]:
df = pd.read_csv(r"D:\python lizong\academic.csv")
df.columns
atribut = ['ID', 'Class', 'Gender', 'Status IMT', 'Berkacamata',
         'Pernah Sakit', 'Gangguan Psikis', 'Aktif Bertanya',
         'Aktif Menjawab', 'Mengerjakan Tugas', 'Tertarik Materi',
         'Alokasi Jam Belajar', 'Memiliki Referensi Tambahan',
        'Browsing dan Youtube', 'Mengulang Materi',
         'Praktek Mandiri', 'Berdiskusi', 'Memiliki HP',
         'Memiliki Laptop', 'Kecukupan Kuota Internet',
         'Dukungan Suasana rumah', 'PLN', 'Lokasi',
         'Ketersediaan Sinyal']
df = pd.read_csv(r"D:\python lizong\academic.csv",names=atribut,skiprows=1)
df.head()

,ID,Class,Gender,Status IMT,Berkacamata,Pernah Sakit,Gangguan Psikis,Aktif Bertanya,Aktif Menjawab,Mengerjakan Tugas,...,Mengulang Materi,Praktek Mandiri,Berdiskusi,Memiliki HP,Memiliki Laptop,Kecukupan Kuota Internet,Dukungan Suasana rumah,PLN,Lokasi,Ketersediaan Sinyal
0,1,0,P,NORMAL,Tidak,Tidak,Tidak,Ya,Ya,Semua,...,Kadang-kadang,Kadang-kadang,Ya,Ya,Ya,Tidak,Kadang-kadang,Ya,Pedesaan,Sebagian
1,2,2,L,GEMUK,Ya,Tidak,Tidak,Tidak,Tidak,Semua,...,Kadang-kadang,Kadang-kadang,Tidak,Ya,Ya,Ya,Ya,Ya,Perkotaan,Ya
2,3,2,P,NORMAL,Ya,Tidak,Tidak,Tidak,Tidak,Semua,...,Kadang-kadang,Kadang-kadang,Ya,Ya,Ya,Ya,Ya,Ya,Perkotaan,Sebagian
3,4,2,P,NORMAL,Tidak,Ya,Tidak,Tidak,Tidak,Semua,...,Kadang-kadang,Ya,Ya,Ya,Ya,Ya,Kadang-kadang,Ya,Perkotaan,Ya
4,5,0,P,NORMAL,Tidak,Ya,Ya,Ya,Ya,Semua,...,Kadang-kadang,Kadang-kadang,Ya,Ya,Ya,Kadang-kadang,Ya,Ya,Perkotaan,Sebagian

In [29]:
df.dtypes

ID                              int64
Class                           int64
Gender                         object
Status IMT                     object
Berkacamata                    object
Pernah Sakit                   object
Gangguan Psikis                object
Aktif Bertanya                 object
Aktif Menjawab                 object
Mengerjakan Tugas              object
Tertarik Materi                object
Alokasi Jam Belajar            object
Memiliki Referensi Tambahan    object
Browsing dan Youtube           object
Mengulang Materi               object
Praktek Mandiri                object
Berdiskusi                     object
Memiliki HP                    object
Memiliki Laptop                object
Kecukupan Kuota Internet       object
Dukungan Suasana rumah         object
PLN                            object
Lokasi                         object
Ketersediaan Sinyal            object
dtype: object

In [132]:
feature_cols = ['Gender', 'Status IMT', 'Berkacamata', 'Pernah Sakit',
                'Gangguan Psikis', 'Aktif Bertanya', 'Aktif Menjawab',
                'Mengerjakan Tugas', 'Tertarik Materi', 
                'Alokasi Jam Belajar', 'Memiliki Referensi Tambahan',
                'Browsing dan Youtube','Mengulang Materi', 'Praktek Mandiri',
                'Berdiskusi', 'Memiliki HP','Memiliki Laptop', 
                'Kecukupan Kuota Internet', 'Dukungan Suasana rumah','PLN', 'Lokasi', 'Ketersediaan Sinyal']
X = df[feature_cols]
y = df.Class

In [156]:
X = pd.get_dummies(X)
X.columns

Index(['Gender_L', 'Gender_P', 'Status IMT_GEMUK', 'Status IMT_KURUS',
       'Status IMT_NORMAL', 'Status IMT_OBESITAS', 'Berkacamata_Tidak',
       'Berkacamata_Ya', 'Pernah Sakit_Tidak', 'Pernah Sakit_Ya',
       'Gangguan Psikis_Tidak', 'Gangguan Psikis_Ya', 'Aktif Bertanya_Tidak',
       'Aktif Bertanya_Ya', 'Aktif Menjawab_Tidak', 'Aktif Menjawab_Ya',
       'Mengerjakan Tugas_Sebagian', 'Mengerjakan Tugas_Semua',
       'Tertarik Materi_Mungkin', 'Tertarik Materi_Tidak',
       'Tertarik Materi_Ya', 'Alokasi Jam Belajar_ANTARA 5 - 10 JAM',
       'Alokasi Jam Belajar_KURANG DARI 5 JAM',
       'Alokasi Jam Belajar_LEBIH DARI 10 JAM',
       'Memiliki Referensi Tambahan_Ada',
       'Memiliki Referensi Tambahan_Tidak Ada', 'Browsing dan Youtube_Tidak',
       'Browsing dan Youtube_Ya', 'Mengulang Materi_Kadang-kadang',
       'Mengulang Materi_Ya', 'Praktek Mandiri_Kadang-kadang',
       'Praktek Mandiri_Ya', 'Berdiskusi_Kadang-kadang', 'Berdiskusi_Tidak',
       'Berdiskusi_Ya', 'Memiliki HP_Tidak', 'Memiliki HP_Ya',
       'Memiliki Laptop_Tidak', 'Memiliki Laptop_Ya',
       'Kecukupan Kuota Internet_Kadang-kadang',
       'Kecukupan Kuota Internet_Tidak', 'Kecukupan Kuota Internet_Ya',
       'Dukungan Suasana rumah_Kadang-kadang', 'Dukungan Suasana rumah_Tidak',
       'Dukungan Suasana rumah_Ya', 'PLN_Tidak', 'PLN_Ya', 'Lokasi_Pedesaan',
       'Lokasi_Perkotaan', 'Lokasi_Pesisir', 'Ketersediaan Sinyal_Sebagian',
       'Ketersediaan Sinyal_Tidak', 'Ketersediaan Sinyal_Ya'],
      dtype='object')

In [160]:
for column in df.columns:
  print(f"Unique Data of Column {column}: ", np.sort(df[column].unique()))

Unique Data of Column ID:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91]
Unique Data of Column Class:  [0 1 2 3]
Unique Data of Column Gender:  ['L' 'P']
Unique Data of Column Status IMT:  ['GEMUK' 'KURUS' 'NORMAL' 'OBESITAS']
Unique Data of Column Berkacamata:  ['Tidak' 'Ya']
Unique Data of Column Pernah Sakit:  ['Tidak' 'Ya']
Unique Data of Column Gangguan Psikis:  ['Tidak' 'Ya']
Unique Data of Column Aktif Bertanya:  ['Tidak' 'Ya']
Unique Data of Column Aktif Menjawab:  ['Tidak' 'Ya']
Unique Data of Column Mengerjakan Tugas:  ['Sebagian' 'Semua']
Unique Data of Column Tertarik Materi:  ['Mungkin' 'Tidak' 'Ya']
Unique Data of Column Alokasi Jam Belajar:  ['ANTARA 5 - 10 JAM' 'KURANG DARI 5 JAM' 'LEBIH DARI 10 JAM']
Unique Data of Column Memiliki Referensi Tambahan:  ['Ada' 'Tidak Ada']
Unique Data of Column Browsing dan Youtube:  ['Tidak' 'Ya']
Unique Data of Column Mengulang Materi:  ['Kadang-kadang' 'Ya']
Unique Data of Column Praktek Mandiri:  ['Kadang-kadang' 'Ya']
Unique Data of Column Berdiskusi:  ['Kadang-kadang' 'Tidak' 'Ya']
Unique Data of Column Memiliki HP:  ['Tidak' 'Ya']
Unique Data of Column Memiliki Laptop:  ['Tidak' 'Ya']
Unique Data of Column Kecukupan Kuota Internet:  ['Kadang-kadang' 'Tidak' 'Ya']
Unique Data of Column Dukungan Suasana rumah:  ['Kadang-kadang' 'Tidak' 'Ya']
Unique Data of Column PLN:  ['Tidak' 'Ya']
Unique Data of Column Lokasi:  ['Pedesaan' 'Perkotaan' 'Pesisir']
Unique Data of Column Ketersediaan Sinyal:  ['Sebagian' 'Tidak' 'Ya']

In [162]:
print(df.isna().sum())

Class                          0
Gender                         0
Status IMT                     0
Berkacamata                    0
Pernah Sakit                   0
Gangguan Psikis                0
Aktif Bertanya                 0
Aktif Menjawab                 0
Mengerjakan Tugas              0
Tertarik Materi                0
Alokasi Jam Belajar            0
Memiliki Referensi Tambahan    0
Browsing dan Youtube           0
Mengulang Materi               0
Praktek Mandiri                0
Berdiskusi                     0
Memiliki HP                    0
Memiliki Laptop                0
Kecukupan Kuota Internet       0
Dukungan Suasana rumah         0
PLN                            0
Lokasi                         0
Ketersediaan Sinyal            0
dtype: int64

In [163]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()
df.iloc[:, 1:] = encoder.fit_transform(df.iloc[:, 1:])
df.head()

,Class,Gender,Status IMT,Berkacamata,Pernah Sakit,Gangguan Psikis,Aktif Bertanya,Aktif Menjawab,Mengerjakan Tugas,Tertarik Materi,...,Mengulang Materi,Praktek Mandiri,Berdiskusi,Memiliki HP,Memiliki Laptop,Kecukupan Kuota Internet,Dukungan Suasana rumah,PLN,Lokasi,Ketersediaan Sinyal
0,0,1.0,2.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,2.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0
1,2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0
2,2,1.0,2.0,1.0,0.0,0.0,0.0,0.0,1.0,2.0,...,0.0,0.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,0.0
3,2,1.0,2.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,2.0,1.0,1.0,2.0,0.0,1.0,1.0,2.0
4,0,1.0,2.0,0.0,1.0,1.0,1.0,1.0,1.0,2.0,...,0.0,0.0,2.0,1.0,1.0,0.0,2.0,1.0,1.0,0.0

In [167]:
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(x, y, random_state = 1)

In [169]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier()
tree.fit(x_train, y_train)

DecisionTreeClassifier()

In [170]:
tree.score(x_val, y_val)

0.6086956521739131

In [171]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(tree, x_val, y_val, cv=5)
print(scores)

[0.4  0.8  0.6  0.75 0.75]